<a href="https://colab.research.google.com/github/cool1014/bigdata-engineer-study/blob/main/%EC%9E%91%EC%97%85%ED%98%951%EC%9C%A0%ED%98%95_%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [146]:
# 빅분기 실기 1유형 30문제 풀이
# 출처 : https://www.youtube.com/watch?v=jRDO3elswQg

In [216]:
import seaborn as sns
import pandas as pd

print(sns.get_dataset_names())

['anagrams', 'anscombe', 'attention', 'brain_networks', 'car_crashes', 'diamonds', 'dots', 'dowjones', 'exercise', 'flights', 'fmri', 'geyser', 'glue', 'healthexp', 'iris', 'mpg', 'penguins', 'planets', 'seaice', 'taxis', 'tips', 'titanic']

In [18]:
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [217]:
print(df.info())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   날짜      11 non-null     object
 1   제품      10 non-null     object
 2   판매량     10 non-null     float64
 3   개당수익    12 non-null     int64
dtypes: float64(1), int64(1), object(2)
memory usage: 516.0+ bytes
None
             판매량        개당수익
count  10.000000   12.000000
mean   15.800000  525.000000
std    11.487191  113.818037
min     3.000000  300.000000
25%    10.000000  475.000000
50%    12.500000  550.000000
75%    18.750000  600.000000
max    40.000000  700.000000

In [218]:
# 1.
result = df['total_bill'].quantile(0.25)
print(round(result))

KeyError: 'total_bill'

In [219]:
# 2.
len(df[df['total_bill'].between(20, 25)])

KeyError: 'total_bill'

In [39]:
# 3. IQR = Q3 - Q1
q3 = df['tip'].quantile(0.75)
q1 = df['tip'].quantile(0.25)
print(q3-q1)

1.5625

In [45]:
# 4.
a = df.sort_values(by = 'tip', ascending = False)
a10 = a.head(10)
# print(a.head(10))
result = a10['tip'].sum()
print(int(result))

70

In [47]:
# 5
result = len(df[df['sex'] == 'Female']) / len(df)
print(round(result, 1))

0.4

In [52]:
# 6
a10 = df.head(10)
result = a10['total_bill'].mean()
print(round(result))

19

In [215]:
# 7

a50 = df.head(122)
result = a50['tip'].median()
print(result)

KeyError: 'tip'

In [60]:
df = sns.load_dataset('mpg')
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [61]:
print(df.describe())

              mpg   cylinders  displacement  horsepower       weight  \
count  398.000000  398.000000    398.000000  392.000000   398.000000
mean    23.514573    5.454774    193.425879  104.469388  2970.424623
std      7.815984    1.701004    104.269838   38.491160   846.841774
min      9.000000    3.000000     68.000000   46.000000  1613.000000
25%     17.500000    4.000000    104.250000   75.000000  2223.750000
50%     23.000000    4.000000    148.500000   93.500000  2803.500000
75%     29.000000    8.000000    262.000000  126.000000  3608.000000
max     46.600000    8.000000    455.000000  230.000000  5140.000000

       acceleration  model_year
count    398.000000  398.000000
mean      15.568090   76.010050
std        2.757689    3.697627
min        8.000000   70.000000
25%       13.825000   73.000000
50%       15.500000   76.000000
75%       17.175000   79.000000
max       24.800000   82.000000

In [64]:
# 8
result = df.isnull().sum().sum()
print(result)

6

In [70]:
# 9
df1 = df.copy()
avg = df['horsepower'].mean()
# print(avg)
df1['horsepower'] = df1['horsepower'].fillna(avg)
result = df1['horsepower'].median()
print(result)

95.0

In [78]:
# 10
df1 = df.copy()
df1 = df1.dropna()
a50 = df1.head(int(len(df1) * 0.5))
print(a50['horsepower'].quantile(0.25))

86.0

In [83]:
# 11
a3 = df[df['cylinders'] == 3]
a8 = df[df['cylinders'] == 8]
result = a3['mpg'].mean() - a8['mpg'].mean()
print(int(abs(result)))

5

In [93]:
# 12  z-score 표준화 : z = (x-평균)/표준편차

a = df['horsepower'].std()
avg = df['horsepower'].mean()
z = (df['horsepower']-avg)/a
# print(z)

print(len(z[z>1.5]) + len(z[z<-1.5]))

39

In [214]:
# 13 min-max-scaling = (x-min)/(max-min)
mms = (df['mpg'] - df['mpg'].min()) / (df['mpg'].max() - df['mpg'].min())
print(len(mms[mms > 0.8]))

KeyError: 'mpg'

In [107]:
# 14
# 이상치 => ub = q3 + 1.5*IQR, lb = q1 - 1.5*IQR

q3, q1 = df['weight'].quantile(0.75), df['weight'].quantile(0.25)
iqr = q3 - q1
ub = q3 + 1.5 * iqr
lb = q1 - 1.5 * iqr

cond1 = df['weight'] > ub
cond2 = df['weight'] < lb

print(len(df[cond1 | cond2]))

0

In [119]:
# 15
a80 = df[df['model_year'] > 80]
a = a80.sort_values(by = 'mpg', ascending = False)
print(a.head(1))

      mpg  cylinders  displacement  horsepower  weight  acceleration  \
394  44.0          4          97.0        52.0    2130          24.6

     model_year  origin       name
394          82  europe  vw pickup

In [128]:
# 16

u = df[df['origin'] == 'usa']['horsepower'].std()
e = df[df['origin'] == 'europe']['horsepower'].std()
print(round(abs(u-e), 1))

19.7

In [137]:
# 17

df1 = df.copy()
avg = df1.groupby(['origin'])['weight'].mean()
# print(avg)
result = df1[(df1['origin'] == 'usa')]['weight'].quantile(0.75)
print(result)

4054.0

In [145]:
# 18
df1 = df.copy()
median = df1.groupby(['name'])['mpg'].median().sort_values(ascending=False)
# print(median)
print(df1[df1['name'] == 'mazda glc']['mpg'].quantile(0.25))

46.6

In [156]:
# 19
df1 = df.copy()
df1 = df1.sort_values(by='horsepower', ascending=False)

df1.loc[:9, 'horsepower'] = 208.0
result = df1[df1['horsepower'] >= 150]['horsepower'].mean()
print(round(result))

172

In [161]:
# 20
result = df1[df1['name'].str.contains('mercury')]['mpg'].mean()
print(int(result))

19

In [164]:
# 21
# 상관계수 df.corr()
df1 = df.copy()
result = df1['horsepower'].corr(df['weight'])
print(round(result, 2))

0.86

In [170]:
# 22
df1 = df.copy()

In [171]:
# 23

In [185]:
df = pd.DataFrame({
    '날짜': ['20220102', '20220105', None, '20230127', '20220203', '20220205', '20220915', '20230301', '20230203', '20230205', '20230315', '20230515'],
    '제품': ['사과', '딸기', None, '딸기', '사과', None, '사과', '딸기', '사과', '딸기', '사과', '사과'],
    '판매량': [3, None, 5, 10, 10, 10, 15, 15, 20, None, 30, 40],
    '개당수익': [300, 400, 500, 600, 400, 500, 500, 600, 600, 700, 600, 600]
})

In [187]:
# 24
df1 = df.copy()
min_v = df1['판매량'].min()
# print(min_v)
avg1 = df1['판매량'].mean()
df1['판매량'] = df1['판매량'].fillna(min_v)
avg2 = df1['판매량'].mean()
print(int(abs(avg1- avg2)))

2

In [194]:
# 25
# 매출액 = 판매량 * 개당수익
# 1분기 =
df1 = df.copy()
df1['매출액'] = df1['판매량'] * df1['개당수익']
df1['날짜'] = pd.to_datetime(df1['날짜'])

result = df1[df1['날짜'].between('2022-01-01', '2022-03-31') & (df['제품'] == '사과')]['매출액'].sum()
print(result)

4900.0

In [205]:
# 26
df1 = df.copy()
df1['매출액'] = df1['판매량'] * df1['개당수익']
df1['날짜'] = pd.to_datetime(df1['날짜'])
s22 = df1[df1['날짜'].between('2022-01-01', '2022-12-31')]['매출액'].sum()
s23 = df1[df1['날짜'].between('2023-01-01', '2023-12-31')]['매출액'].sum()
print(abs(s22-s23))

51600.0

In [220]:
# 27
df1 = df.copy()
df1['매출액'] = df1['판매량'] * df1['개당수익']
df1['날짜'] = pd.to_datetime(df1['날짜'])
print(df1[df1['날짜'].between('2022-01-01', '2022-12-31')])

          날짜    제품   판매량  개당수익     매출액
0 2022-01-02    사과   3.0   300   900.0
1 2022-01-05    딸기   NaN   400     NaN
4 2022-02-03    사과  10.0   400  4000.0
5 2022-02-05  None  10.0   500  5000.0
6 2022-09-15    사과  15.0   500  7500.0

In [213]:
# 28

In [228]:
# min-max-scailing
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df['컬럼'] = scaler.fit_transform(df[['컬럼']])
df[['여러컬럼', '여러컬럼']] = scaler.fit_transform(df[['여러컬럼', '여러컬럼']])

['__annotations__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__sklearn_clone__', '__sklearn_tags__', '__str__', '__subclasshook__', '__weakref__', '_build_request_for_signature', '_check_feature_names', '_check_n_features', '_doc_link_module', '_doc_link_template', '_doc_link_url_param_generator', '_get_default_requests', '_get_doc_link', '_get_metadata_request', '_get_param_names', '_get_tags', '_more_tags', '_parameter_constraints', '_repr_html_', '_repr_html_inner', '_repr_mimebundle_', '_reset', '_sklearn_auto_wrap_output_keys', '_validate_data', '_validate_params', 'clip', 'copy', 'feature_range', 'fit', 'fit_transform', 'get_feature_names_out', 'get_metadata_routing', 'get_params', 'inverse_transform', 'partial_fit', 'set_output', 'set_params', 'transform']